2020-12-20 19:19:30,077 ERROR: Exception on /user/Akshay [GET] [in /home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/app/routes.py", line 74, in user
    return render_template('user.html', user=user,posts = posts.items, next_url= next_url, prev_url = prev_url ,form = form)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/app/templates/base.html", line 53, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/app/templates/user.html", line 16, in block "app_content"
    <p><a href="{{ url_for('main.edit_profile') }}">{{ _('Edit your profile') }}</a></p>
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.edit_profile'. Did you mean 'edit_profile' instead?
2020-12-20 19:21:31,217 INFO: Microblog startup [in /home/akshay/Documents/flask-projects/microblog/micro-venv/app/__init__.py:46]
2020-12-20 19:21:39,381 ERROR: Exception on /edit_profile [GET] [in /home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/app/routes.py", line 97, in edit_profile
    return render_template('edit_profile.html',title='Edit Profile', form = form)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/app/templates/edit_profile.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/app/templates/base.html", line 53, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/app/templates/edit_profile.html", line 7, in block "app_content"
    {{ wtf.quick_form(form) }}
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'wtf' is undefined
2020-12-20 19:24:44,217 INFO: Microblog startup [in /home/akshay/Documents/flask-projects/microblog/micro-venv/app/__init__.py:46]
